"""
Generate question node for both start and answer workflows.

Generates exactly ONE interview question based on the current strategy.
"""

from app.graph.state import InterviewState
from app.graph.utils import format_question
from app.llm.model import llm
from app.prompts.templates import GENERATE_QUESTION_PROMPT
from app.prompts.output_models import QuestionOutput


def generate_question(
    state: InterviewState,
) -> dict:

    question_llm = llm.with_structured_output(
        QuestionOutput
    )

    prev_summary = (
        state["prev_summary"]
        if state["prev_summary"]
        else "No previous interview history. This is the first question."
    )

    prompt = GENERATE_QUESTION_PROMPT.format(

        # Interview
        role=state["role"],
        experience=state["experience"],
        mode=state["mode"],

        # Candidate
        skills=state["skills"],
        projects=state["projects"],
        exp=state["exp"],
        resumeText=state["resumeText"],

        # Memory
        prev_summary=prev_summary,

        # Current interaction
        cur_question=format_question(
            state["cur_question"]
        ),
        cur_answer=state["cur_answer"],

        # Follow-up
        follow_up_allowed=state["follow_up_allowed"],
        follow_up_context=state["follow_up_context"],
        follow_up_cnt=state["follow_up_cnt"],
        follow_up_score=state["follow_up_score"],

        # Topic
        recent_topic=state["recent_topic"],
        topic_coverage=state["topic_coverage"],

        # Strategy
        next_focus=state["next_focus"],
        next_topic=state["next_topic"],
        next_difficulty=state["next_difficulty"],
        next_question_type=state["next_question_type"],
    )

    result: QuestionOutput = question_llm.invoke(
        prompt
    )

    return {
        "next_question": {
            "question": result.question,

            # These are controlled by the strategy agent.
            "difficulty": state["next_difficulty"],
            "questionType": state["next_question_type"],

            # Generated by the question generator.
            "timeLimit": result.timeLimit,
        }
    }
